spring.application.name=EmpTrack

spring.datasource.url=jdbc:mysql://localhost:3306/spring_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true





#.....Help Spring to execute(data.sql) after Hibernate creates tables.........#
spring.jpa.defer-datasource-initialization=true

#......... To take data from data.sql.......#
spring.sql.init.mode=always